# apply via
# conda env create -f environment.yml
# conda activate dagster-asset-demo
# conda remove --name dagster-asset-demo --all
#name: dagster-asset-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - nb_conda
  - ipywidgets
  - jupyterlab-git
  - yarn
  - nodejs
  - python>=3.8
  - git
  - mamba
  - pandas
  - numpy
  - scipy
  - pyarrow
  - pygit2
  - sqlalchemy
  - sqlite
  - mock
  - requests
  - ratelimit 
  - pandera
  - pyspark
  - seaborn
  - matplotlib
  - scikit-learn
  - python-duckdb
  - pytest
  - pip
  - pip:
      - dagster
      - dagster-shell
      - dagster-pandas
      - dagster-pandera
      - dagster-postgres
      - dagster-airbyte
      - dagster-dbt
      - dagster-pyspark
      - dagster-slack
      - dagstermill
      - dbt-core
      - dbt-sqlite
      - dbt-postgres
      - dbt-duckdb
      - dagit
      # - acryl-datahub
      # - polars
