version: 2

models:
  - name: story_daily_stats
    description: Summary of posting activity by day
    columns:
      - name: date
        description: The date that the stories were posted on.
      - name: num_stories
        description: The number of stories posted.
      - name: posting_users
        description: The number of unique users who posted a story.
  - name: comment_daily_stats
    description: Summary of comment activity by day
    columns:
      - name: date
        description: The date that the stories were posted on.
      - name: num_comments
        description: The number of comments posted.
      - name: posting_users
        description: The number of unique users who posted a comment.
  - name: activity_daily_stats
    description: Combined stats about activity on each day
    columns: []
